#! /bin/bash

readonly BASEDIR="$(dirname $(readlink -f "$0"))"
readonly BASEURL="http://nexus.sonatype.org/downloads"
readonly BINARY="nexus-oss-webapp-1.9.2.3-bundle.tar.gz"

set -e
mkdir -p "${BASEDIR}/SOURCES/"
cd "${BASEDIR}/SOURCES/"
wget "${BASEURL}/${BINARY}"
