#! /bin/bash

readonly BASEDIR="$(dirname $(readlink -f "$0"))"
readonly BASEURL="http://www.sonatype.org/downloads"
readonly BINARY="nexus-latest-bundle.tar.gz"

set -e
cd "${BASEDIR}/SOURCES/"
wget "${BASEURL}/${BINARY}"

